### PR TITLE
make jlpcb file generation automatic

### PR DESCRIPTION
**Pull request by 1zun4**
This GitHub workflow will automatically generate the requires files for JLPCB for every change, making it easier to keep track of it and prevents you from always having to push them yourself if asked for. I am not 100% sure if the settings are correct, so please check them. @badgineer 

As soon this has been merged you can active this workflow under "Action" if not already enabled and trigger it manually if needed via clicking on the workflow and pressing "Run workflow" (This workflow has a workflow_dispatch event trigger).

Required files for JLPCB:

- [x] Gerber
- [x] Excellon (waiting for https://github.com/INTI-CMNB/KiBot/issues/322)
- [x] BOM (waiting for https://github.com/INTI-CMNB/KiBot/issues/322)
- [x] CPL

### CODE REVIEW

**Comment by 1zun4** [comment]
I have tried adding automatic BOM file generation but seems it cannot handle the references in the kicad schematic
```
ERROR:While loading `/github/workspace/versions/v0.1/CCC_ESC.kicad_sch` (kibot - kiplot.py:259)
ERROR:Malformed component reference `12V1` (kibot - kiplot.py:260)
```

**Comment by 1zun4** [comment]
grafik
grafik

Gerber file generation and position works flawless. What is up with the BOM file generation... I don't know.

**Comment by 1zun4** [comment]
grafik

BOM generation now works as well.

**Comment by 1zun4** [comment]
grafik

Easy. @badgineer 
It should be fine now.

**Review by badgineer — APPROVED** [review]
Danke!

**Pull request merged**
